### PR TITLE
Rethemed and updated basically the entire extension.

### PR DESCRIPTION
**Pull request by ErikBoesen**

### CODE REVIEW

**Comment by corbindavenport** [comment]
Wow, I think that's the most someone has contributed to one of my repos. If you want, you can fork this repo and take over development yourself since it's not on the Chrome Web Store at all, and I can just link this repo to yours.

**Comment by ErikBoesen** [comment]
Can I just be added as a collaborator? I think that would be easier.

**Comment by corbindavenport** [comment]
Done :)

**Comment by ErikBoesen** [comment]
Thanks! Glad I can be of assistance.

**Pull request merged**
